name: Bug Report
description: Report a problem, broken link, or visual glitch.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please be descriptive.

  - type: input
    id: url
    attributes:
      label: Page URL
      description: Where did this happen?
      placeholder: https://shridhan.com/products/...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Device
      description: e.g., Chrome on Windows, Safari on iPhone
      placeholder: Chrome / Windows 10
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to see the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: The menu should have opened.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The screen went white.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please drag and drop screenshots here.
      placeholder: Drag images here or paste from clipboard...
    validations:
      required: false
