name: 🔧 Bug Report
description: Report defects, broken functionality, or display issues (WARRANTY)
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Use this template to report actual defects, broken functionality, or display issues.
        
        **Note:** Bugs are covered under warranty. For content changes, use the Content Update template.

  - type: input
    id: url
    attributes:
      label: Page URL
      description: Where did this happen?
      placeholder: https://shridhan.softeem.org/products/...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Device
      description: e.g., Chrome on Windows, Safari on iPhone
      placeholder: Chrome / Windows 10
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to see the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: The menu should have opened.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The screen went white or text is overlapping.
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What kind of bug is this?
      options:
        - Display Issue (overlapping, alignment)
        - Broken Functionality
        - Typography Error (missing letters, symbols)
        - Performance Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please drag and drop screenshots here
      placeholder: Drag images here or paste from clipboard...
    validations:
      required: false
