name: 💰 Content Update Request
description: Request changes to text, images, or content ordering (BILLABLE)
title: "[Content]: "
labels: ["content-update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Content Update Request
        Use this template to request changes to existing content such as text updates, image replacements, or content reordering.
        
        **Note:** This is billable work. Content updates are tracked separately from bug fixes.

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Which page needs the content update?
      placeholder: https://shridhan.softeem.org/...
    validations:
      required: true

  - type: dropdown
    id: update-type
    attributes:
      label: Type of Content Update
      description: What type of content needs to be updated?
      options:
        - Text/Copy Update
        - Image Replacement
        - Content Reordering
        - Contact Information
        - Multiple Updates
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: Describe or paste the current content that needs to be changed
      placeholder: |
        Example: The current text says "Lorem ipsum..." 
        Or: The current image shows [description]
    validations:
      required: true

  - type: textarea
    id: requested-content
    attributes:
      label: Requested Content
      description: Provide the new content or describe the changes needed
      placeholder: |
        Example: Please change the text to "New content here..."
        Or: Please replace the image with [attached/linked image]
        Or: Please reorder items as: 1. Item A, 2. Item B, 3. Item C
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or files that would help
      placeholder: |
        - Screenshots showing current vs. desired state
        - Links to new images
        - Any specific formatting requirements

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this update?
      options:
        - Low (Can wait)
        - Medium (Normal timeline)
        - High (Needed soon)
        - Urgent (ASAP)
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have provided the page URL
          required: true
        - label: I have clearly described both current and requested content
          required: true
        - label: I have attached any necessary images or files
          required: false
