name: Feature Request
description: A new idea, layout change, or content structure update.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please explain *why* this is needed.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
      placeholder: I need to click 3 times to see the Middle East address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: When I click 'Middle East', the address should slide down...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Did you think of other ways?
      placeholder: We could also just list all addresses on one page...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Mockups
      description: Please drag and drop images here to show us what you mean.
      placeholder: Drag images here...
    validations:
      required: false
