name: 🚀 Enhancement Request
description: Suggest new features or structural improvements (BILLABLE)
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Request
        Use this template to suggest new features, structural changes, or improvements beyond the original scope.
        
        **Note:** This is billable work. Enhancements are tracked separately from bug fixes.

  - type: textarea
    id: problem
    attributes:
      label: Is your enhancement related to a problem?
      description: Describe the problem or limitation you're experiencing
      placeholder: |
        Example: Currently, users cannot [do something]...
        Or: The navigation structure doesn't support [use case]...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the Enhancement
      description: What would you like to see added or changed?
      placeholder: |
        Example: Add a new section for [feature]...
        Or: Restructure the navigation to include [changes]...
        Or: Implement [new functionality]...
    validations:
      required: true

  - type: dropdown
    id: enhancement-type
    attributes:
      label: Type of Enhancement
      description: What category does this enhancement fall into?
      options:
        - New Feature/Section
        - Navigation/Structure Change
        - Layout Improvement
        - Functionality Addition
        - Integration/API
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions or features you've considered

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: |
        - Screenshots or mockups
        - Examples from other sites
        - Specific requirements

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this enhancement?
      options:
        - Low (Nice to have)
        - Medium (Would improve UX)
        - High (Important for business)
        - Critical (Blocking workflow)
      default: 1
    validations:
      required: true
